CableApp/urls.py
from django.urls import path
from .views import addCable, deleteCableRun, deleteConduitRun,deleteConduit, deleteCable

app_name = "CableApp"

urlpatterns = [
    # path('/addcable', addCable,  name='cable-home'),
    path('addCable/', addCable, name='add-cable'),
    path('deleteConduitRun/<id>', deleteConduitRun, name='deleteConduitRun'),
    path('deleteCableRun/<id>', deleteCableRun, name='deleteCableRun'),
    path('deleteConduit/<id>', deleteConduit, name='deleteConduit'),
    path('deleteCable/<id>', deleteCable, name='deleteCable'),

]

user_management/urls.py
from django.contrib import admin

from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, ResetPasswordView, ChangePasswordView

from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls')),

#     path('', include('CableApp.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    path("__reload__/", include("django_browser_reload.urls")),

    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from .views import home, profile, RegisterView

urlpatterns = [
    path('', home, name='users-home'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('profile/', profile, name='users-profile'),
    path('', include('CableApp.urls'), name='CableApp'),
]

CableApp/models.py
from django.db import models

# Create your models here.
class Cable(models.Model): #standard cable library
    name = models.CharField(max_length=50, null=True)
    size = models.CharField(max_length=50, null=True)
    rating = models.CharField(max_length=50, null=True)
    conductors = models.CharField(max_length=50, null=True)
    OuterDimension = models.FloatField(max_length=50, null=True)
        
    def __str__(self):
        return self.name

class CableRun(models.Model): #project cables
    cabletag       = models.CharField(max_length=200)
    length         = models.CharField(max_length=200)
    cable          = models.ForeignKey(Cable, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.cabletag
    
class Conduit(models.Model): #standard conduit library
    name           = models.CharField(max_length=50, null=True)
    InnerDimension = models.FloatField(max_length=200, null=True)
    OuterDimension = models.FloatField(max_length=200, null=True)
    Area           = models.FloatField(max_length=200, null=True)

    def calculate_area(Innerdimension):
        result = 3.14*(Innerdimension/2)**2
        return result

    def __str__(self):
        return self.name
    
class ConduitRun(models.Model): #project conduit 
    conduittag = models.CharField(max_length=200)
    conduit = models.ForeignKey(Conduit, on_delete=models.CASCADE)
    cable = models.ManyToManyField(CableRun)
    fill = models.FloatField(max_length=200, null=True)

    # def calculate_fill(cabledims):
    #     cabledims
    #     totalarea
    #     return fillpct

    def __str__(self):
        return self.conduittag

CableApp/forms.py
from django import forms
from .models import Cable, CableRun, Conduit, ConduitRun

class CableForm(forms.ModelForm):
    class Meta:
        model = Cable
        fields = '__all__'

class CableRunForm(forms.ModelForm):
    class Meta:
        model = CableRun
        fields = '__all__'

class ConduitForm(forms.ModelForm):
    class Meta:
        model = Conduit
        fields = ['name', 'InnerDimension', 'OuterDimension']

class ConduitRunForm(forms.ModelForm):
    class Meta:
        model = ConduitRun
        fields = ['conduittag', 'conduit', 'cable']

CableApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Cable, Conduit, CableRun, ConduitRun
from .forms import CableForm, ConduitForm,ConduitRunForm,CableRunForm
from django.urls import reverse

# Create your views here.
@login_required
def addCable(request):
    form = CableForm()
    form1 = ConduitForm()
    form2 = CableRunForm()
    form3 = ConduitRunForm()
    conduits = Conduit.objects.all()
    cables = Cable.objects.all()
    conduitruns = ConduitRun.objects.all()
    cableruns = CableRun.objects.all()
    # print(conduitruns,"this is the cables assigned to this conduit")
    # print(cableruns,"is the cable runs")
    # conduitruns

        
        
    if request.method == 'POST':
        # print(request.POST)
        if 'addcable' in request.POST:
            form = CableForm(request.POST)
            if form.is_valid():
                form.save()
        elif 'addconduit' in request.POST:
            form1 = ConduitForm(request.POST)
            if form1.is_valid():
                form1.save()
        elif 'projectcable' in request.POST:
            form2 = CableRunForm(request.POST)
            if form2.is_valid():
                form2.save()
        elif 'projectconduit' in request.POST:
            form3 = ConduitRunForm(request.POST)
            if form3.is_valid():
                form3.save()

    for conduit in conduits:
        conduit.Area = Conduit.calculate_area(conduit.InnerDimension)
        conduit.save()

    for conduitrun in conduitruns:
        sumlist = []
        cablelist = conduitrun.cable.all()
        for cable in cablelist:
            result = 3.14*(cable.cable.OuterDimension/2)**2
            sumlist.append(result)
        totalcablearea = sum(sumlist)
        conduitrun.fill = (totalcablearea / conduitrun.conduit.Area)

    context = {'form':form,'form1':form1,'conduits':conduits, 'cables':cables,
            'conduitruns':conduitruns,'cableruns':cableruns,'form2':form2,'form3':form3, 
               }
    return render(request, 'addcable.html',context)


@login_required
def deleteConduitRun(request, id):
    try:
        rtd = ConduitRun.objects.get(pk=id)
        rtd.delete()
        return redirect(reverse('CableApp:add-cable'))
    except ConduitRun.DoesNotExist:
        print("ohno")
        return redirect(reverse('CableApp:add-cable'))

@login_required
def deleteCableRun(request, id):
    try:
        rtd = CableRun.objects.get(pk=id)
        rtd.delete()
        return redirect(reverse('CableApp:add-cable'))
        # context = {'id':id,}
    except CableRun.DoesNotExist:
        print("ohno")
        return redirect(reverse('CableApp:add-cable'))

@login_required
def deleteConduit(request, id):
    try:
        rtd = Conduit.objects.get(pk=id)
        rtd.delete()
        return redirect(reverse('CableApp:add-cable'))
        # context = {'id':id,}
    except Conduit.DoesNotExist:
        print("ohno")
        return redirect(reverse('CableApp:add-cable'))
    
@login_required
def deleteCable(request, id):
    try:
        rtd = Cable.objects.get(pk=id)
        rtd.delete()
        return redirect(reverse('CableApp:add-cable'))
        # context = {'id':id,}
    except Cable.DoesNotExist:
        print("ohno")
        return redirect(reverse('CableApp:add-cable'))

CableApp/templates/addcable.html
<!-- {% extends "./base.html" %} -->
{% block title %} Home Page {% endblock title%}
{% block content %}


{% if user.is_authenticated %}
<form action="" method="post">
    <h3>Step 1: Fill out your cable library</h3>
    {% csrf_token %}
    {{form}}
    <button name="addcable" value="addcable">Add Cable</button>
</form>   
<div>
    <br>
    <h5>These are the standard library cables</h5>
    <table border="1">
        <tr>
            <th>Cable Name</th>
            <th>Cable Size</th>
            <th>Cable Conductors</th>
            <th>Cable Rating</th>
            <th>Cable Outer Dimension</th>
        </tr>
        {%for cable in cables%}
        <tr>
            <td>{{cable.name}} </td>
            <td>{{cable.size}} </td>
            <td>{{cable.conductors}} </td>
            <td>{{cable.rating}} </td>
            <td>{{cable.OuterDimension}} </td>
            <td><a href="{% url 'CableApp:deleteCable' cable.id %}"class="nav-item nav-link">delete</a></td>
        </tr>
        {%endfor%}
    </table>
    <br>
    <form action="" method="post">
        <h3>Step 2: Fill out your conduit library</h3>
        {% csrf_token %}
        {{form1}}
        <button name="addconduit" value="addconduit">Add Conduit</button>
    </form>  
    <h5>These are the standard library conduits</h5>
    <table border="1">
        <tr>
            <th>Conduit Part Number</th>
            <th>Conduit Inner Dimension</th>
            <th>Conduit Outer Dimension</th>
        </tr>
        {%for conduit in conduits%}
        <tr>
            <td>{{conduit.name}} </td>
            <td>{{conduit.InnerDimension}} </td>
            <td>{{conduit.OuterDimension}}   </td>
            <td><a href="{% url 'CableApp:deleteConduit' conduit.id %}"class="nav-item nav-link">delete</a></td>
        </tr>
        {%endfor%}
    </table>
    <br>
    <form action="" method="post">
        <h3>Step 3: assign project cables from your standard library</h3>
        {% csrf_token %}
        {{form2}}
        <button name="projectcable" value="projectcable">Add Project Cable</button>
    </form>  
    <h5>These are your project cables</h5>
    <table border="1">
        <tr>
            <th>Cable Tag</th>
            <th>Cable Length</th>
            <th>Cable Name</th>
            <th>Cable Size</th>
            <th>Cable Rating</th>
            <th>Cable Conductors</th>
        </tr>
        {%for cable in cableruns%}
        <tr>
            <td>{{cable.cabletag}} </td>
            <td>{{cable.length}} </td>
            <td>{{cable.cable.name}} </td>
            <td>{{cable.cable.size}} </td>
            <td>{{cable.cable.rating}} </td>
            <td>{{cable.cable.conductors}} </td>
            <td><a href="{% url 'CableApp:deleteCableRun' cable.id %}"class="nav-item nav-link">delete</a></td>
        </tr>
        {%endfor%}
    </table>
    <br>
    <form action="" method="post">
        <h3>Step 4: assign project conduits and designate which cables are inside</h3>
        {% csrf_token %}
        {{form3}}
        <button name="projectconduit" value="projectconduit">Add Project Conduit</button>
    </form>  
    <h5>These are your project conduits</h5>
    <table border="1">
        <tr>
            <th>Conduit Tag</th>
            <th>Conduit Inner Dimension</th>
            <th>Cables Assigned</th>
            <th>Conduit Area</th>
            <th>Conduit Fill Pct</th>
        </tr>
        {%for conduit in conduitruns%}
        <tr>
    
            <td>{{conduit.conduittag}} </td>
            <td>{{conduit.conduit.InnerDimension}} </td>
            <td> 
                {% for conduitrun_cable in conduit.cable.all%}
                    {{conduitrun_cable}}    
                {% endfor %}
            </td>
            <td>{{conduit.conduit.Area}}</td>
            <td>{{conduit.fill}}</td> 
            <td><a href="{% url 'CableApp:deleteConduitRun' conduit.id %}"class="nav-item nav-link">delete</a></td>
        {%endfor%}


        <!-- {%for cable in cablelist%}
        {%endfor%} -->
            <!-- <td>{{cable.rating}} </td> -->
            <!-- {{ forloop.counter0 }} -->
        </tr>

    </table>
    </div>

{% else %}
<a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Sign in</a>
{% endif %}
{% endblock content %}

CableApp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <title>{% block title %} {% endblock %} </title>
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
          <a href="/" class="navbar-brand">Home</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                    <a href="{% url 'users-profile' %}" class="nav-item nav-link">Profile</a>
                    <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                  {% else %}
                    <a href="{% url 'login' %}" class="nav-item nav-link">Sign in</a>
                  {% endif %}

                </div>
            </div>
        </nav>
        <!--Any flash messages pop up in any page because this is the base template-->
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- A plugin for password show/hide  -->
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

</body>
</html>

CableApp/templates/delete.html
{% extends "users/base.html" %}
{% block title %} Home Page {% endblock title%}
{% block content %}


Hello!
{{id}}
{% endblock content %}